// src/content/en.ts
// English locale content for Marhaban Canada

import type { LocaleContent, StepGuide, StepId } from './fr';

const buildStepsRecord = (steps: StepGuide[]) =>
  steps.reduce((acc, step) => {
    acc[step.id] = step;
    return acc;
  }, {} as Record<StepId, StepGuide>);

const enSteps: StepGuide[] = [
  {
    id: "nas",
    title: "Social Insurance Number (SIN)",
    description: "Used for work, paying taxes, and accessing certain services.",
    href: "/parcours/guide/steps/nas",
    summary: "Your SIN links you to taxes, employment, and federal programs. Without it, no employer can legally pay you.",
    what: "The SIN is a unique number issued by Service Canada that proves you are authorized to work or receive benefits.",
    why: "It secures your tax record and helps prevent identity theft.",
    how: [
      "Book a visit to a Service Canada Centre (or apply online if your case allows).",
      "Bring your passport, study or work permit, and proof of Canadian address.",
      "Keep the SIN letter in a physical folder, never share this number via messaging.",
    ],
    avoid: [
      "Only give your SIN to a confirmed employer, your bank, or authorities.",
      "Refuse any paid offer promising a faster SIN.",
    ],
    sources: [{ name: "Service Canada", url: "https://www.canada.ca/en/employment-social-development/services/social-insurance-number.html" }],
  },
  {
    id: "health",
    title: "Provincial Health Card",
    description: "Access to the public system in your province of arrival.",
    href: "/parcours/guide/steps/health",
    summary: "Each province manages its health insurance. Until your card is active, urgent care can be very expensive.",
    what: "The health card proves your eligibility for the public plan (RAMQ, OHIP, MSP, etc.).",
    why: "It covers essential medical consultations and avoids high upfront costs.",
    how: [
      "Check your provincial website to confirm forms and waiting periods.",
      "Gather ID, permit, and proof of residency (lease, bill).",
      "Submit your application online or in person, then monitor your mail.",
    ],
    avoid: [
      "Do not lie about your arrival date or address: the card may be canceled.",
      "Beware of non-government websites that charge for free forms.",
    ],
    sources: [{ name: "IRCC – Healthcare", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/learn-about-canada/health-care/health-care-system.html" }],
  },
  {
    id: "bank",
    title: "Bank Account",
    description: "Structure your finances and build your credit history.",
    href: "/parcours/guide/steps/bank",
    summary: "Opening a local account facilitates employer transfers, renting a home, and access to newcomer products.",
    what: "A Canadian account and a secured credit card allow you to receive income, pay, and build your credit score.",
    why: "Banks often require an active account to verify identity and reduce fraud.",
    how: [
      "Compare newcomer programs (reduced fees, international transfers).",
      "Book an appointment at a branch with passport, permit, and proof of address.",
      "Ask for a secured credit card or a suitable newcomer program.",
    ],
    avoid: ["Never share your PIN or banking codes.", "Do not sign up for any product whose fees you don't understand."],
    sources: [{ name: "FCAC – Open an account", url: "https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html" }],
  },
  {
    id: "phone",
    title: "Phone / SIM",
    description: "Get a local number for procedures and communications.",
    href: "/parcours/guide/steps/phone",
    summary: "A local number facilitates identity verification and avoids exorbitant roaming charges.",
    what: "This involves purchasing a Canadian SIM/eSIM and choosing a plan suitable for your first month.",
    why: "Administrative procedures often require a local number to confirm an account.",
    how: [
      "Compare newcomer plans from Bell, Rogers, and Telus, and prepaid options.",
      "Buy your SIM at the airport or an official store to activate immediately.",
      "Keep the receipt to prove your address or arrival date if requested.",
    ],
    avoid: ["Avoid buying a SIM from unauthorized resellers.", "Do not share your portability codes or online account details."],
    sources: [{ name: "ISED – Wireless services", url: "https://www.ic.gc.ca/eic/site/smt-gst.nsf/eng/sf11467.html" }],
  },
  {
    id: "housing",
    title: "Housing Search",
    description: "Show a clean record and know provincial rules.",
    href: "/parcours/guide/steps/housing",
    summary: "A written and compliant lease protects your rights. Serious landlords require a complete file even without local history.",
    what: "The tenant file includes proof of income, references, and a legal deposit according to the province.",
    why: "It reduces the risk of scams and helps you rent under clear conditions.",
    how: [
      "Prepare your rental CV, bank statements, and employment or support letter.",
      "Plan visits (physical or video) and verify the landlord's identity.",
      "Read every clause of the lease and pay via traceable methods after signing.",
    ],
    avoid: ["Never transfer money before having a signed lease.", "Refuse requests for unnecessary copies of SIN or passport."],
    sources: [
      { name: "IRCC – Housing", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/life-in-canada/housing.html" },
      { name: "CMHC", url: "https://www.cmhc-schl.gc.ca/en/consumers" },
    ],
  },
];

export const enContent: LocaleContent = {
  locale: "en",
  dir: "ltr",
  brand: "Marhaban Canada",
  contactEmail: "contact@marhabancanada.ca",

  hero: {
    title: "Your arrival in Canada, one click at a time.",
    subtitle: "Every step is explained simply with official sources.",
    ctaPrimary: "See the checklist",
    ctaSecondary: "Explore sources",
  },

  microcopy: {
    homeTitle: "First steps after arriving in Canada",
    homeSubtitle: "Marhaban Canada is a support and orientation service for newcomers to Canada.",
    homeCtaPrimary: "Start the journey",
    homeCtaSub: "Free · Based on official sources · No registration required",
    journeyTitle: "Your settlement journey",
    journeySubtitle: "The simplest order to start stress-free.",
    phaseWeek1Title: "Week 1",
    phaseWeek1Desc: "These steps get you operational quickly. One at a time, at your own pace.",
    phaseMonth1Title: "Month 1",
    phaseMonth1Desc: "Nothing urgent. Proceed when you feel ready.",
    phaseOngoingTitle: "Ongoing",
    phaseOngoingDesc: "Keep these in mind for the weeks to come.",
    breadcrumbHome: "Home",
    breadcrumbJourney: "Journey",
    breadcrumbGuide: "Guide",
    breadcrumbBlog: "Blog",
    youAreHere: "You are here",
    statusInStep: "You are at step {step} ({phase}). Good starting point.",
    nextStepLabel: "Next step",
    backLabel: "Back",
    backToJourneyLabel: "Back to journey",
    recommendedNextStepTitle: "Recommended next step",
    recommendedNextStepDesc: "Whenever you're ready, you can move to the next step.",
    viewGuideCta: "View guide",
    relatedArticlesTitle: "Related articles",
    priorityReadsTitle: "Priority reads",
    priorityReadsDesc: "If you just arrived, start with these articles.",
    searchPlaceholder: "Search (housing, credit, SIN...)",
    mottoLabel: "The motto",
    docsLabel: "What you need (nothing more)",
    smartTipsLabel: "Good to know (useful tips)",
    guideStartLabel: "Start of guide",
    guideEndLabel: "End of guide",
    noCommitmentLabel: "No commitment · You can change later.",
    continueWhenReadyLabel: "When you're ready, you can continue.",
    whyIntroLabel: "Without this step, several procedures become complicated.",
    howIntroLabel: "Follow these steps in order. Nothing complicated.",
    docsIntroLabel: "Prepare these documents before going.",
    avoidIntroLabel: "To avoid absolutely (for your safety)",
  },

  serviceAccompagnementDefinition: {
    title: "Support Service",
    body: "A service that guides, explains, and directs newcomers, step by step, without performing procedures on their behalf and without charging for official services.",
  },
  serviceAccompagnementWhatIs: [
    "Clear orientation for newcomers",
    "Simple explanation of official procedures",
    "Help to understand the logical order of steps",
    "Prevention of errors and scams",
    "Redirection to official sources only",
    "Human, reassuring, and non-judgmental support",
  ],
  serviceAccompagnementWhatIsNot: [
    "This is not a government service",
    "This is not an immigration service",
    "This is not a paid agent or consultant",
    "We do not fill out any forms for you",
    "We do not make any appointments for you",
    "We do not charge for any official services",
  ],
  serviceAccompagnementWhatIsTitle: "What this service is",
  serviceAccompagnementWhatIsNotTitle: "What this service is not",
  serviceAccompagnementNoProxy: "We do not perform any official procedures on your behalf.",
  serviceAccompagnementPillar: "Marhaban Canada is a support and orientation service for newcomers to Canada.",
  serviceAccompagnementDisclaimer: "This site offers a support and orientation service. It does not replace official government services.",

  seoDescriptions: {
    meta: "Support service for newcomers to Canada: official procedures, housing, banking, phone, scam prevention.",
    og: "Support service for newcomers to Canada: official procedures, housing, banking, phone, scam prevention.",
    pdfHeader: "Support service for newcomers to Canada: official procedures, housing, banking, phone, scam prevention.",
  },

  services: {
    title: "Priority Services",
    cards: [
      {
        title: "Administrative settlement",
        description: "Health card, banks, and essential protections.",
        icon: "home",
        sources: [{ name: "Service Canada", url: "https://www.canada.ca/en/employment-social-development.html" }],
      },
      {
        title: "Reliable housing",
        description: "Tenant file, lease reading, warning signs.",
        icon: "shield",
        sources: [{ name: "CMHC", url: "https://www.cmhc-schl.gc.ca/en/consumers" }],
      },
      {
        title: "Local career",
        description: "Canadian CV, interviews, official salary standards.",
        icon: "briefcase",
        sources: [{ name: "Job Bank", url: "https://www.jobbank.gc.ca" }],
      },
      {
        title: "Provincial networks",
        description: "Francophone organizations, community resources.",
        icon: "globe",
        sources: [{ name: "IRCC", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html" }],
      },
    ],
  },

  navLinks: [
    { label: "Services", href: "#services" },
    { label: "Steps", href: "#steps" },
    { label: "Budget", href: "#budget" },
    { label: "Guides", href: "/parcours/guide" },
    { label: "Sources & Reliability", href: "/sources" },
    { label: "Legal / Disclaimer", href: "/mentions" },
  ],

  checklist: {
    title: "Your first 5 steps",
    subtitle: "1 click = 1 detailed page. Check and progress at your own pace.",
    shareLabel: "Share my progress",
    resetLabel: "Reset",
    shareSuccess: "Progress copied, you can send it.",
    shareError: "Cannot share now.",
    items: enSteps,
  },

  steps: buildStepsRecord(enSteps),

  survival48h: {
    title: "48h Plan",
    subtitle: "Stabilize transport, temporary accommodation, and connectivity.",
    items: [
      {
        title: "Leaving the airport",
        description: "REM Montreal, UP Express Toronto, and Canada Line Vancouver offer safe and traceable journeys.",
        href: "https://tc.canada.ca/en/transport-services.html",
        sources: [{ name: "Transport Canada", url: "https://tc.canada.ca" }],
      },
      {
        title: "Getting around the city",
        description: "Buy your OPUS, PRESTO, or Compass card upon arrival to benefit from local fares.",
        href: "https://www.canada.ca/en.html",
        sources: [{ name: "Local Authorities", url: "https://www.canada.ca/en.html" }],
      },
      {
        title: "Temporary accommodation",
        description: "Prioritize student residences open to newcomers or city-listed hostels.",
        href: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants.html",
        sources: [{ name: "IRCC", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html" }],
      },
      {
        title: "Canadian SIM",
        description: "Bell, Rogers, and Telus kiosks at the airport offer newcomer plans without credit.",
        href: "https://www.ic.gc.ca/eic/site/smt-gst.nsf/eng/sf11467.html",
        sources: [{ name: "ISED", url: "https://www.ic.gc.ca" }],
      },
    ],
  },

  budget: {
    title: "Estimated Monthly Budget",
    subtitle: "Survival basket = rent + groceries + transport x household profile.",
    note: "Amounts come from official cities or agencies and are regularly updated.",
    cityLabel: "Choose a city",
    householdLabel: "Household composition",
    totalLabel: "Estimated basket",
    breakdownLabels: { rent: "Rent", groceries: "Groceries", transport: "Transport" },
    households: [
      { id: "solo", label: "1 adult", multiplier: 1 },
      { id: "couple", label: "Couple", multiplier: 1.35 },
      { id: "famille", label: "Family (3+)", multiplier: 1.6 },
    ],
    cities: [
      {
        id: "montreal",
        label: "Montreal",
        rent: 1500,
        groceries: 420,
        transport: 94,
        cityMultiplier: 1,
        sources: [{ name: "CMHC", url: "https://www.cmhc-schl.gc.ca/en/consumers" }],
      },
      {
        id: "toronto",
        label: "Toronto",
        rent: 2200,
        groceries: 520,
        transport: 156,
        cityMultiplier: 1.2,
        sources: [{ name: "City of Toronto", url: "https://www.toronto.ca" }],
      },
      {
        id: "calgary",
        label: "Calgary",
        rent: 1750,
        groceries: 450,
        transport: 112,
        cityMultiplier: 1.05,
        sources: [{ name: "City of Calgary", url: "https://www.calgary.ca" }],
      },
    ],
  },

  resourceSources: [
    {
      title: "Find a Francophone clinic",
      description: "List of Francophone community clinics by province.",
      href: "https://santefrancais.ca",
      sources: [{ name: "Réseau Santé en français", url: "https://santefrancais.ca" }],
    },
    {
      title: "IRCC Integration Programs",
      description: "Free workshops for CVs, housing, and rights.",
      href: "https://ircc.canada.ca/english/services/immigrate-canada/settle.asp",
      sources: [{ name: "IRCC", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html" }],
    },
    {
      title: "Consumer Protection",
      description: "Anti-fraud guide for rentals and purchases.",
      href: "https://www.canada.ca/en/financial-consumer-agency.html",
      sources: [{ name: "FCAC", url: "https://www.canada.ca/en/financial-consumer-agency.html" }],
    },
  ],

  resources: {
    header: {
      title: "Official and Community Resources",
      subtitle: "Verified links, categorized by need.",
      searchPlaceholder: "Search for a resource (housing, health, employment...)",
      provinceLabel: "Province",
      categoryLabel: "Category",
    },
    accompaniment: {
      shortDefinition: "This site offers a support and orientation service. It does not replace official government services.",
      noProxyLine: "We do not perform any official procedures on your behalf.",
      footerHelp: "Need help knowing what to do first? The support service can guide you according to your situation.",
    },
    quickGuides: {
      documentsCard: {
        title: "Essential Documents",
        body: "Prepare your papers once to avoid blockages.",
        ctaLabel: "View documents checklist",
        href: "/checklist",
      },
      transportCard: {
        title: "Transport and permits",
        body: "Understand local rules before driving.",
        ctaLabel: "View transport resources",
        href: "/resources",
      },
      creditCard: {
        title: "Credit and banking",
        body: "Avoid mistakes that last a long time.",
        ctaLabel: "View banking guide",
        href: "/parcours/guide/steps/bank",
      },
    },
    sections: {
      arrival: { title: "Arrival", hint: "To consult upon arrival to understand official steps." },
      housing: { title: "Housing", hint: "To consult before any visit or deposit." },
      health: { title: "Health", hint: "To do upon arrival, even if the card has not yet been received." },
      jobs: { title: "Employment", hint: "Useful for finding a job without falling into traps." },
      documents: { title: "Documents", hint: "To prepare your papers once, and save time." },
      transport: { title: "Transport", hint: "To understand permits and transport according to your province." },
      credit: { title: "Credit", hint: "Useful from the first month to avoid long-lasting mistakes." },
      taxes: { title: "Taxes", hint: "To keep your documents and avoid tax stress." },
      integration: { title: "Integration", hint: "To find local help and reliable services." },
    },
    ui: {
      recommendedStart: "⭐ Recommended to start",
      openResource: "Open resource",
      addFavorite: "Add to favorites",
      seeGuide: "View associated guide →",
      backToPath: "Return to journey →",
    },
  },

  resourcesPage: {
    labels: {
      eyebrow: "Resources",
      title: "Official and Community Resources",
      subtitle: "Verified links, categorized by need.",
      searchPlaceholder: "Search (immigration, health, employment...)",
      provinceLabel: "Province",
      categoryLabel: "Category",
      filterAll: "All",
      officialLabel: "Official",
      recommendedLabel: "Recommended",
      openLabel: "Open resource",
      addFavoriteLabel: "Add to favorites",
      removeFavoriteLabel: "Remove from favorites",
      emptyState: "No resources match this search.",
      allProvincesLabel: "Canada",
      guideCalloutTitle: "The watchword",
      guideWhatTitle: "What it is",
      guideWhyTitle: "Why it's important",
      guideHowTitle: "How to do it",
      guidePitfallsTitle: "Pitfalls to avoid",
      guideActionsTitle: "Direct actions",
      guideSourcesTitle: "Official sources",
      guideActionPrompt: "Ready to take action?",
      guideEyebrow: "Guide",
    },
    provinceOptions: [
      { value: "qc", label: "Quebec" },
      { value: "on", label: "Ontario" },
      { value: "bc", label: "British Columbia" },
      { value: "ab", label: "Alberta" },
      { value: "other", label: "Other province" },
    ],
    categories: [
      { id: "arrival", title: "Arrival", description: "Status, procedures, and settlement." },
      { id: "housing", title: "Housing", description: "Lease, deposit, local rules." },
      { id: "health", title: "Health", description: "Health card, coverage, clinics." },
      { id: "employment", title: "Employment", description: "Offers, rights, standards." },
      { id: "documents", title: "Documents", description: "Essential papers and copies." },
      { id: "transport", title: "Transport", description: "Permits and transport cards." },
      { id: "credit", title: "Credit", description: "Score and best practices." },
      { id: "taxes", title: "Taxes", description: "Annual declaration and documents." },
      { id: "integration", title: "Integration", description: "Local services and networks." },
    ],
    items: {
      "arrival-services": { title: "Newcomer services", description: "Welcome info and official services." },
      ircc: { title: "IRCC - immigration", description: "Official portal for immigration." },
      cmhc: { title: "CMHC - housing", description: "Housing advice and information." },
      "tal-qc": { title: "Administrative Housing Tribunal (QC)", description: "Rental rules and rights in Quebec." },
      "health-card": { title: "Health Insurance Card", description: "Official process + provincial links." },
      ramq: { title: "RAMQ (Quebec)", description: "Quebec health coverage." },
      ohip: { title: "OHIP (Ontario)", description: "Ontario health coverage." },
      msp: { title: "MSP (British Columbia)", description: "BC health coverage." },
      ahcip: { title: "AHCIP (Alberta)", description: "Alberta health coverage." },
      jobbank: { title: "Job Bank", description: "Official job offers." },
      "labour-standards": { title: "Labour standards", description: "Official rights and protections." },
      "documents-guide": { title: "Documents Guide", description: "Checklist of documents to prepare." },
      "transport-guide": { title: "Transport Guide", description: "Permits + procedures by province." },
      "credit-guide": { title: "Credit Guide", description: "Score and clean start." },
      driving: { title: "Driver's license", description: "Official Canada information." },
      saaq: { title: "SAAQ (Quebec)", description: "Permits and vehicles in Quebec." },
      "service-ontario-driving": { title: "ServiceOntario - permits", description: "Permits and roads in Ontario." },
      icbc: { title: "ICBC (BC)", description: "Permits and insurance in BC." },
      "alberta-registries": { title: "Alberta registries", description: "Permits and services in Alberta." },
      "credit-score": { title: "Credit score (FCAC)", description: "Understand and improve your score." },
      taxes: { title: "Taxes (CRA)", description: "Annual declaration and documents." },
      integration: { title: "211 Canada", description: "Quick local help." },
    },
    guides: {
      documents: {
        title: "Essential Documents",
        summary: "Prepare your papers once, save time at each step.",
        callout: "One clear copy means one less hour of stress.",
        what: "Essential documents are used for all procedures (employment, health, housing).",
        why: ["Avoid administrative blockages", "Save time", "Protect your originals"],
        how: ["Scan passport and permits", "Create a digital folder", "Print key copies", "Store an offline copy"],
        pitfalls: ["Sharing your documents without verification", "Losing originals", "Not backing up copies"],
        actions: ["Prepare a personal checklist", "Create a secure cloud folder"],
        ctaLabel: "Documents checklist to prepare",
        ctaHref: "/checklist",
        sources: [{ name: "IRCC", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html" }],
      },
      transport: {
        title: "Transport and Permits",
        summary: "Understand the procedures according to your province.",
        callout: "A valid permit = freedom + safety.",
        what: "Permits and transport cards vary by province.",
        why: ["Avoid fines", "Move easily", "Valid insurance"],
        how: ["Check provincial rules", "Prepare documents", "Book tests if required"],
        pitfalls: ["Driving without a valid permit", "Ignoring conversion deadlines"],
        actions: ["Choose temporary transport mode", "Plan an appointment"],
        ctaLabel: "View permit procedures (by province)",
        ctaHref: "https://www.canada.ca/en/services/transport/driving.html",
        sources: [{ name: "Canada.ca", url: "https://www.canada.ca/en/services/transport.html" }],
      },
      credit: {
        title: "Credit and Score",
        summary: "Start cleanly and avoid mistakes.",
        callout: "Small start, big impact in the long run.",
        what: "Credit score impacts housing, loans, and services.",
        why: ["Negotiate better rates", "Facilitate renting", "Build financial reputation"],
        how: ["Apply for a suitable card", "Pay on time", "Limit usage"],
        pitfalls: ["Late payments", "Excessive utilization"],
        actions: ["Monitor your score regularly", "Maintain a clean history"],
        ctaLabel: "Understand score + start cleanly",
        ctaHref: "https://www.canada.ca/en/financial-consumer-agency/services/credit.html",
        sources: [{ name: "FCAC", url: "https://www.canada.ca/en/financial-consumer-agency.html" }],
      },
    },
  },

  guideOrder: ["nas", "health", "bank", "phone", "housing"],

  guides: {
    nas: {
      slug: "nas" as const,
      title: "SIN (Service Canada)",
      icon: "IdCard",
      urgency: 9,
      sections: {
        description: {
          text: "The SIN is the Social Insurance Number that allows you to work legally and access federal programs.",
          sources: [{ name: "Service Canada", url: "https://www.canada.ca/en/employment-social-development/services/social-insurance-number.html" }],
        },
        why: {
          text: "Without a SIN, your employer cannot pay you or report your deductions, and some tax credits will be blocked.",
          sources: [{ name: "Canada Revenue Agency", url: "https://www.canada.ca/en/revenue-agency.html" }],
        },
        documents: {
          items: ["Valid passport", "Study or work permit", "Proof of Canadian address (lease, bill, welcome letter)"],
          sources: [{ name: "Service Canada – Accepted documents", url: "https://www.canada.ca/en/employment-social-development/services/social-insurance-number/documents.html" }],
        },
        where: {
          text: "Visit a Service Canada Centre or use the official online procedure if eligible.",
          sources: [{ name: "Find a Service Canada Centre", url: "https://catalogue.servicecanada.gc.ca/services/centre-service-canada" }],
        },
        cost: {
          text: "Free – no company is authorized to charge you for obtaining a SIN.",
          sources: [{ name: "Service Canada – SIN FAQ", url: "https://www.canada.ca/en/employment-social-development/services/social-insurance-number/questions.html" }],
        },
        proTip: {
          text: "Scan your SIN letter, keep it offline, and never share your number via SMS or messaging.",
          sources: [{ name: "Service Canada – Protect your SIN", url: "https://www.canada.ca/en/employment-social-development/services/social-insurance-number/protect.html" }],
        },
        fraudAlert: {
          text: "No agent will ask for your SIN by phone to unlock a file. Hang up and contact Service Canada directly.",
          sources: [{ name: "RCMP – Fraud", url: "https://www.rcmp-grc.gc.ca/en/renting-scams" }],
        },
      },
    },
    health: {
      slug: "health" as const,
      title: "Provincial Health Card",
      icon: "HeartPulse",
      urgency: 8,
      sections: {
        description: {
          text: "Each province issues its health insurance card (RAMQ, OHIP, MSP, etc.) which covers essential care.",
          sources: [{ name: "IRCC – Healthcare", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/learn-about-canada/health-care/health-care-system.html" }],
        },
        why: {
          text: "Some provinces have a waiting period; without a card, a simple visit can be very expensive.",
          sources: [{ name: "Government of Quebec – RAMQ", url: "https://www.quebec.ca/en/health/health-insurance" }],
        },
        documents: {
          items: ["Passport and permit (work, study, or permanent residence)", "Proof of residency (lease, energy bill)", "Completed provincial form"],
          sources: [{ name: "Ontario – OHIP", url: "https://www.ontario.ca/page/apply-ohip-and-get-health-card" }],
        },
        where: {
          text: "Apply to the provincial agency (RAMQ, ServiceOntario, Service BC) or online if available.",
          sources: [{ name: "ServiceOntario", url: "https://www.ontario.ca/page/serviceontario" }],
        },
        cost: {
          text: "Free: the card is free, but temporary private insurance may be useful during the waiting period.",
          sources: [{ name: "Government of B.C. – MSP", url: "https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/msp/bc-residents/eligibility-and-enrolment" }],
        },
        proTip: {
          text: "Subscribe to temporary insurance (travel/student) until your provincial coverage is activated.",
          sources: [{ name: "IRCC – Private insurance", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/health-care/private-health-insurance.html" }],
        },
        fraudAlert: {
          text: "Forms are free: avoid sites that charge processing fees.",
          sources: [{ name: "Consumer Protection Ontario", url: "https://www.ontario.ca/page/consumer-protection-ontario" }],
        },
      },
    },
    bank: {
      slug: "bank" as const,
      title: "Bank Account",
      icon: "Wallet",
      urgency: 7,
      sections: {
        description: {
          text: "Canadian banks offer newcomer packages to manage your money from the start.",
          sources: [{ name: "FCAC – Newcomer offers", url: "https://www.canada.ca/en/financial-consumer-agency/services/banking/banking-offers-newcomers.html" }],
        },
        why: {
          text: "A local account facilitates direct deposits, traceable payments for housing, and credit building.",
          sources: [{ name: "FCAC – Credit", url: "https://www.canada.ca/en/financial-consumer-agency/services/credit.html" }],
        },
        documents: {
          items: ["Passport and permit (work, study, or permanent residence)", "Proof of Canadian address", "SIN (optional but often requested)"],
          sources: [{ name: "FCAC – Open an account", url: "https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html" }],
        },
        where: {
          text: "Book an appointment at a branch (or online) with a recognized bank/credit union.",
          sources: [{ name: "FCAC – List of banks", url: "https://www.canada.ca/en/financial-consumer-agency/services/banking/banks-list.html" }],
        },
        cost: {
          text: "Often: free monthly fees for 12 months with newcomer programs, then standard rates.",
          sources: [{ name: "FCAC – Newcomer offers", url: "https://www.canada.ca/en/financial-consumer-agency/services/banking/banking-offers-newcomers.html" }],
        },
        proTip: {
          text: "Ask for a secured credit card to start your history with controlled risk.",
          sources: [{ name: "FCAC – Secured cards", url: "https://www.canada.ca/en/financial-consumer-agency/services/credit-cards/secured-credit-cards.html" }],
        },
        fraudAlert: {
          text: "Never pay to reserve a bank appointment and refuse any transfer to a personal account.",
          sources: [{ name: "FCAC – Prevent fraud", url: "https://www.canada.ca/en/financial-consumer-agency/services/fraud-prevention.html" }],
        },
      },
    },
    phone: {
      slug: "phone" as const,
      title: "Phone and Data",
      icon: "PhoneCall",
      urgency: 6,
      sections: {
        description: {
          text: "A Canadian number facilitates identity verification (banks, online services) and account security.",
          sources: [{ name: "ISED – Wireless services", url: "https://www.ic.gc.ca/eic/site/smt-gst.nsf/eng/sf11467.html" }],
        },
        why: {
          text: "Many services use verification SMS to secure account access.",
          sources: [{ name: "CRTC – Wireless Services Code", url: "https://crtc.gc.ca/eng/phone/mobile/wirelesscode.htm" }],
        },
        documents: {
          items: ["Passport or photo ID", "Local contact information (address and email)", "Optional: creditworthiness for postpaid plans"],
          sources: [{ name: "CRTC – Wireless Code", url: "https://crtc.gc.ca/eng/phone/mobile/wirelesscode.htm" }],
        },
        where: {
          text: "Buy a SIM/eSIM via an official kiosk (airport, store) or directly from a recognized operator.",
          sources: [{ name: "CRTC – Providers", url: "https://crtc.gc.ca/eng/phone/mobile/tel.htm" }],
        },
        cost: {
          text: "Prepaid plans vary by province and promotions; BYOD is often the best start.",
          sources: [{ name: "ISED – Comparator", url: "https://www.ic.gc.ca/eic/site/086.nsf/eng/00006.html" }],
        },
        proTip: {
          text: "Prioritize BYOD (bring your own device) to avoid a long commitment before having a credit history.",
          sources: [{ name: "CRTC – Wireless Code", url: "https://crtc.gc.ca/eng/phone/mobile/wirelesscode.htm" }],
        },
        fraudAlert: {
          text: "Beware of unauthorized resellers, cash deposits, and too good to be true promises. Demand an official receipt.",
          sources: [{ name: "ISED – Anti-fraud tips", url: "https://www.ic.gc.ca/eic/site/mc-cm.nsf/eng/h_lm04321.html" }],
        },
      },
    },
    housing: {
      slug: "housing" as const,
      title: "Rental Housing",
      icon: "Home",
      urgency: 8,
      sections: {
        description: {
          text: "Renting involves a written lease compliant with provincial rules and a credible tenant file.",
          sources: [{ name: "IRCC – Housing", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/life-in-canada/housing.html" }],
        },
        why: {
          text: "An official lease protects your deposit, clarifies rules, and reduces risks of abuse.",
          sources: [{ name: "CMHC – Tenant rights", url: "https://www.cmhc-schl.gc.ca/en/consumers" }],
        },
        documents: {
          items: ["Employment letter or proof of income", "Rental or professional references", "Bank statements or proof of savings"],
          sources: [{ name: "CMHC – Prepare your file", url: "https://www.cmhc-schl.gc.ca/en/consumers/renting/prepare-your-housing-search" }],
        },
        where: {
          text: "Visit the accommodation (physical/video) and verify the landlord's identity via reliable sources.",
          sources: [{ name: "Administrative Housing Tribunal (QC)", url: "https://www.tal.gouv.qc.ca/en" }],
        },
        cost: {
          text: "The legal deposit varies by province. Do not accept requests beyond what is permitted.",
          sources: [{ name: "Ontario – Deposits", url: "https://www.ontario.ca/page/renting-your-home-rights-and-responsibilities" }],
        },
        proTip: {
          text: "Pay by traceable means (transfer/cheque) and send a summary email after each visit.",
          sources: [{ name: "FCAC – Traceable payments", url: "https://www.canada.ca/en/financial-consumer-agency/services/electronic-transfers.html" }],
        },
        fraudAlert: {
          text: "No signed lease = no money. Beware of ads that refuse visits.",
          sources: [{ name: "RCMP – Rental fraud", url: "https://www.rcmp-grc.gc.ca/en/renting-scams" }],
        },
      },
    },
  },

  globalDisclaimer: "Information and guidance only. Always verify conditions on official websites before proceeding.",

  antiFraud: {
    title: "Integrity and anti-fraud",
    body: "We do not expedite any visas, do not fabricate any documents, and systematically refer to government websites.",
    note: "Report any suspicious behavior to CBSA or IRCC (official link in each step).",
  },

  scams: {
    microcopy: {
      searchPlaceholder: "Search for a scam (housing, employment...)",
      frequentTitle: "Frequent scams",
      startHousingTitle: "Start with housing",
      startHousingText: "If you are asked to pay before a visit, stop everything: it's a very common scam red flag.",
      startHousingSubtext: "Examples, warning signs and what to do.",
      startHousingCta: "View housing scams →",
      startHousingCtaAria: "View housing-related scams",
      breadcrumb: { home: "Home", scams: "Scams" },
      backToScams: "Back to scams",
      goToJourney: "Go to journey",
      notFound: "Guide not found. Return to scam categories to choose a valid guide.",
      needMoreTitle: "Need to go further?",
      needMoreText: "Consult the housing guide to understand the steps and avoid mistakes.",
      needMoreCta: "See housing guide →",
      housingLabel: "Housing",
      pageEyebrow: "Scams",
      pageTitle: "Frequent Scams: How to spot them in 2 minutes",
      pageSubtitle: "You are not alone. The goal: understand, avoid, act.",
      rulesTitle: "Golden Rules",
      planTitle: "5-Step Action Plan",
      planSubtitle: "Simple, fast, without panic.",
      categoriesTitle: "Scam Categories",
      planLinkLabel: "5-Step Action Plan",
      victimTitle: "I think I am a victim: what should I do?",
      victimSubtitle: "5-step action plan, don't panic.",
      victimPlanSteps: [
        "Don't panic and stop all payments immediately.",
        "Keep all evidence (screenshots, emails, conversations, receipts).",
        "Contact your bank or financial institution to block transactions.",
        "Report the scam to the police (police report) and the appropriate organization (e.g., CAFC for financial fraud).",
        "Consult official resources to understand your legal options and protect your identity.",
      ],
    },
    housing: {
      rules: ["Never pay before a visit.", "Refuse anonymous transfers (crypto, gift cards).", "Verify the landlord and address."],
      planSteps: ["Request a real visit.", "Verify the ad (photos, address, price).", "Sign an official lease only after visiting."],
    },
    guides: {
      logement: {
        subtitle: "Common scams related to renting.",
        scenario: [
          "Ad too good to be true (low price, perfect photos).",
          "The landlord is abroad and cannot show the property.",
          "Request for money transfer before any visit or lease signing.",
          "Pressure to decide quickly and pay immediately.",
        ],
        redFlags: [
          "Request for a high security deposit or non-refundable application fees.",
          "Communication only by email or instant messaging, never by phone.",
          "Refusal to provide a physical address or show the property.",
          "Lease agreement with unusual or abusive clauses.",
        ],
        actions: [
          "Demand a physical visit to the property.",
          "Verify the landlord's identity and the legality of the ad.",
          "Never transfer money before signing a legal lease and receiving the keys.",
          "Use traceable payment methods (check, bank transfer).",
        ],
        mantra: "No visit = no money.",
      },
      emploi: {
        subtitle: "Scams related to job offers and recruitment.",
        scenario: [
          "Unsolicited job offer with an unrealistic salary.",
          "Request for payment for equipment, training, or a background check.",
          "Job interview via instant messaging without voice or video contact.",
          "Pressure to provide personal information (SIN, bank account) too early.",
        ],
        redFlags: [
          "Spelling and grammar errors in the job offer.",
          "Generic email address (Gmail, Outlook) for the recruiter.",
          "Abnormally fast recruitment process without verification.",
          "Request to buy back equipment with promised reimbursement.",
        ],
        actions: [
          "Research the company and recruiter on LinkedIn or their official website.",
          "Never pay for a job or application fees.",
          "Never provide SIN or bank details before a signed contract.",
          "Use the official Job Bank to verify the legitimacy of offers.",
        ],
        mantra: "A real job never asks for fees.",
      },
      telephone: {
        subtitle: "Scams related to mobile plans and phone services.",
        scenario: [
          "Unsolicited calls promising incredible discounts on plans.",
          "Pressure to change provider or subscribe to unwanted options.",
          "Surprise billing with hidden fees or unauthorized services.",
          "Theft of personal data under the guise of account verification.",
        ],
        redFlags: [
          "Offers too good to be true, today only.",
          "Request for personal information (password, SIN) by phone.",
          "Aggressive representative or refusal to provide clear information.",
          "Difficulty canceling a service or getting a refund.",
        ],
        actions: ["Never share sensitive information by phone.", "Check offers on official websites.", "Read contracts carefully.", "Contact CRTC or the operator in case of dispute."],
        mantra: "Read everything, especially the fees.",
      },
      banque: {
        subtitle: "Financial and banking scams.",
        scenario: [
          "Calls or emails pretending to be your bank asking for confidential information.",
          "Pressure to make an urgent transfer to secure your account.",
          "Offers of loans or credit cards without credit check (too easy).",
          "Phishing: fake banking websites to steal your credentials.",
        ],
        redFlags: ["Request for your PIN, password, or verification codes.", "Extreme urgency, threats.", "Suspicious links in emails or SMS.", "Spelling errors."],
        actions: ["Never click on suspicious links.", "Contact your bank via the official number.", "Verify the URL (https, padlock).", "Report fraud attempts."],
        mantra: "Your bank never asks for your PIN.",
      },
      immigration: {
        subtitle: "Scams related to immigration services and fake consultants.",
        scenario: [
          "Promises of guaranteed visas or permanent residency, without conditions.",
          "Request for high payment for free services.",
          "Fake immigration agents contacting you by email or phone.",
          "Request for original documents or cash.",
        ],
        redFlags: ["Hidden fees.", "Pressure to act quickly.", "Unofficial payments (crypto, gift cards).", "Lack of license."],
        actions: ["Verify legitimacy on official websites.", "Never pay for free services.", "Never send originals.", "Keep all evidence."],
        mantra: "No one can guarantee a visa.",
      },
      marketplace: {
        subtitle: "Scams when buying or selling on online platforms.",
        scenario: [
          "Seller asking for upfront payment via an insecure method.",
          "Buyer offering to pay more and asking for a refund.",
          "Pressure to finalize off-platform.",
          "Product not as described after payment.",
        ],
        redFlags: ["Recent profile.", "Refusal to meet.", "Request for codes.", "Generic messages."],
        actions: ["Hand-to-hand delivery.", "Secure payments if possible.", "Beware of offers too good to be true.", "Report profiles."],
        mantra: "No meeting = no purchase.",
      },
    },
  },

  guidePage: {
    subtitle: "5 steps ranked by urgency to guide you even when mental load is high.",
    ctaLabel: "Start with SIN",
    infoPill: "5 priority steps",
    priorityLegend: "Priority displayed: 10 = immediate, 1 = plan soon.",
    timelineTitle: "Express journey",
    timelineSubtitle: "Understand the order of execution without reading all the sheets in detail.",
    groups: [
      { title: "Status & health", description: "Secure your right to work and your medical coverage before the rest.", slugs: ["nas", "health"] },
      { title: "Daily setup", description: "Prepare your finances, phone, and housing.", slugs: ["bank", "phone", "housing"] },
    ],
  },

  newsletter: {
    title: "Join the community",
    description: "One email per month with official reminders and anti-scam alerts.",
    placeholder: "your.email@email.com",
    cta: "Subscribe",
    successTitle: "Welcome!",
    successBody: "You will receive our official resources very soon.",
    error: "Not possible right now. Try again later.",
  },

  floatingCta: { label: "Need help?", href: "mailto:contact@marhabancanada.ca" },

  footer: {
    disclaimer: "Information and support service. Does not replace government services. Official procedures must always be validated on government websites.",
    rights: "© 2025 Marhaban Canada. All rights reserved.",
  },

  shared: {
    sourceLabel: "Source",
    officialLink: "Official link",
    budgetLegend: "Rent + transport + groceries x household coefficient.",
    disclaimer: "Information and guidance only. Always refer to official websites.",
    radarTitle: "Anti-scam radar",
    radarBody: "Always check senders, refuse gift card payments, and keep digital copies of your evidence.",
    sourcesIntro: "Every recommendation is based on a verifiable government or quasi-public website.",
    viewAllSteps: "View all steps",
    sectionLabels: {
      what: "What is it?",
      why: "Why is it important?",
      how: "How to do it",
      avoid: "To avoid",
      sources: "Official sources",
      docs: "Required documents",
      smartTips: "Good to know",
    },
    easyReadOn: "Easy Read Mode",
    easyReadOff: "Normal Mode",
    ctas: {
      start: "Start",
      startJourney: "Start the journey",
      viewChecklist: "View checklist",
      viewJourney: "View journey",
      viewGuides: "View guides",
      viewGuide: "View guide",
      findOffice: "Find an office",
      backToHome: "Back to home",
      continue: "Continue",
      next: "Next",
      previous: "Previous",
      download: "Download",
      share: "Share",
      reset: "Reset",
      search: "Search",
      filter: "Filter",
      all: "All",
    },
    commonPhrases: {
      whyItMatters: "Why it matters",
      whatYouNeed: "What you need",
      stepByStep: "Step by step",
      importantNote: "Important note",
      warning: "Warning",
      tip: "Tip",
      remember: "Remember",
      avoid: "To avoid",
      sources: "Sources",
      official: "Official",
      recommended: "Recommended",
      urgent: "Urgent",
      optional: "Optional",
    },
    scamLabels: {
      scenario: "The scenario",
      redFlags: "Red flags",
      actions: "Actions to take",
      neverDo: "Never do",
      mantra: "The mantra",
      victimPlan: "Action plan if you are a victim",
    },
    nav: {
      home: "Home",
      checklist: "Checklist",
      parcours: "Journey",
      ressources: "Resources",
      arnaques: "Scams",
      about: "About",
      contact: "Contact",
      legal: "Legal",
      plus: "More",
      switchToFr: "FR",
      switchToEn: "EN",
      switchToAr: "AR",
    },
  },

  howToUsePage: {
    title: "How to use this site",
    whatThisSiteDoes: {
      title: "What this site does",
      items: [
        "Provides reliable and verified information to help you settle in Canada.",
        "Offers an interactive checklist to track your steps.",
        "Explains complex steps in simple language.",
        "Shares official sources for each piece of information.",
        "Highlights common mistakes to avoid.",
      ],
    },
    whatThisSiteDoesNotDo: {
      title: "What this site does NOT do",
      items: [
        "Does NOT replace the services of a lawyer or immigration consultant.",
        "Does NOT collect any personal data (your progress is saved locally on your device).",
        "Does NOT guarantee obtaining documents or services (each case is unique).",
        "Does NOT provide personalized legal or financial advice.",
        "Does NOT help you fill out forms or make appointments.",
      ],
    },
    howToUseItStepByStep: {
      title: "How to use it step by step",
      items: [
        "Start with the checklist to get an overview.",
        "Click on each step to access the detailed guide.",
        "Check off the steps you have completed to track your progress.",
        "Use the 'Official Sources' links to verify the information.",
        "Enable 'Easy Read Mode' if you prefer more spaced out text.",
        "Don't hesitate to check the 'Scams' section to avoid traps.",
      ],
    },
  },

  contactPage: {
    title: "Contact",
    question: "Do you have a question or suggestion?",
    writeToUs: "Write to us at",
    privacy: "No personal data is collected via this contact channel.",
    responseTime: "We reply as soon as possible.",
    disclaimer: "Information and support service. Does not replace government services. Official procedures must always be validated on government websites.",
    intro: "We're here to help. Ask your question and we'll reply quickly.",
    safetyNote: "Never share your SIN, passwords, or banking information by email.",
    formName: "Name",
    formEmail: "Email",
    formMessage: "Message",
    formTopic: "Topic",
    formTopicOptions: [
      { value: "general", label: "General question" },
      { value: "checklist", label: "Checklist" },
      { value: "scams", label: "Scams" },
      { value: "technical", label: "Technical issue" },
      { value: "other", label: "Other" },
    ],
    formSubmit: "Send message",
    formSuccess: "Message sent successfully. We'll reply soon.",
    formError: "An error occurred. Please try again later.",
    secondaryLinks: {
      legal: "Legal",
      scams: "Scams",
      checklist: "Checklist",
    },
  },

  aboutPage: {
    title: "About Marhaban Canada",
    intro: "A support and orientation service to simplify your settlement in Canada.",
    mission: {
      title: "Our mission",
      content: "Marhaban Canada is a support and orientation service for newcomers to Canada. We simplify settlement by providing clear information based on official sources.",
    },
    whatWeDo: {
      title: "What the platform does",
      items: [
        "Provides reliable and verified information to help you settle in Canada.",
        "Offers an interactive checklist to track your steps.",
        "Explains complex steps in simple language.",
        "Shares official sources for each piece of information.",
        "Highlights common mistakes to avoid.",
      ],
    },
    whatWeDontDo: {
      title: "What the platform does not do",
      items: [
        "Does not replace immigration law firm services.",
        "Does not collect any personal data (your progress is saved locally on your device).",
        "Does not guarantee obtaining documents or services (each case is unique).",
        "Does not provide personalized legal or financial advice.",
        "Does not help you fill out forms or book appointments.",
      ],
    },
    sources: {
      title: "How we choose sources",
      intro: "We select only official and verifiable sources. Here are some examples:",
      examples: [
        "Service Canada (SIN, permits, etc.)",
        "IRCC (Immigration, Refugees and Citizenship Canada)",
        "RAMQ, OHIP, MSP (provincial health cards)",
        "FCAC (Financial Consumer Agency of Canada)",
        "Provincial and municipal government websites",
      ],
    },
    cta: {
      label: "Start the checklist",
      href: "/checklist",
    },
  },

  legalPage: {
    title: "Legal",
    editor: {
      title: "Site editor",
      content: "Marhaban Canada is an independent, non-governmental information and support service. This site is published by Marhaban Canada.",
    },
    usage: {
      title: "Use of information",
      content: "The information on this site is provided for informational purposes only. It does not constitute legal, financial, or professional advice. Always verify information on official government websites.",
    },
    responsibilities: {
      title: "Responsibilities and limitations",
      content: "Marhaban Canada cannot be held responsible for decisions made based on the information provided. Each situation is unique and requires verification with the competent authorities. We do not guarantee the accuracy, completeness, or currency of the information.",
    },
    dataProtection: {
      title: "Data protection",
      what: "We do not collect any personal data through this site. Your progress in the checklist is saved only on your device (localStorage).",
      why: "No data is transmitted to our servers. Everything remains local on your browser.",
      retention: "Locally stored data can be deleted at any time via the Reset button in the checklist.",
    },
    cookies: {
      title: "Cookies and local storage",
      content: "This site uses only your browser's local storage (localStorage) to save your progress in the checklist. No tracking cookies are used. You can delete this data at any time via your browser settings.",
    },
    intellectualProperty: {
      title: "Intellectual property",
      content: "The content of this site (texts, structure, design) is protected by copyright. The official sources cited remain the property of their respective publishers (governments, public organizations).",
    },
    contact: {
      title: "Legal contact",
      email: "contact@marhabancanada.ca",
    },
  },
};
