import type { Booking, CaseFile, ResourceGuide, ScamCheck } from '@/types/admin';

export const mockBookings: readonly Booking[] = [
  {
    id: 'bk_1001',
    createdAt: '2026-06-14T14:20:00.000Z',
    fullName: 'Nadia Benali',
    email: 'nadia.benali@example.com',
    phone: '+1 514 555 0123',
    cityProvince: 'Montréal, QC',
    service: 'orientation',
    serviceLabel: 'Appel orientation — 45 min',
    duration: '45 min',
    price: 'À venir',
    status: 'new',
    clientStatus: 'newcomer',
    preferredLanguage: 'fr',
    message: "Je viens d'arriver et je veux prioriser NAS, banque et assurance santé.",
    nextAction: 'Répondre avec 2 créneaux cette semaine.',
  },
  {
    id: 'bk_1002',
    createdAt: '2026-06-15T09:45:00.000Z',
    fullName: 'Omar Haddad',
    email: 'omar.haddad@example.com',
    cityProvince: 'Ottawa, ON',
    service: 'discovery',
    serviceLabel: 'Appel découverte gratuit — 15 min',
    duration: '15 min',
    price: 'Gratuit',
    status: 'to_contact',
    clientStatus: 'student',
    preferredLanguage: 'ar',
    message: 'Je suis étudiant international et je ne sais pas quoi faire en premier.',
    nextAction: 'Envoyer disponibilité courte + lien ressources étudiants.',
  },
  {
    id: 'bk_1003',
    createdAt: '2026-06-15T18:05:00.000Z',
    fullName: 'Maya Singh',
    email: 'maya.singh@example.com',
    phone: '+1 647 555 0188',
    cityProvince: 'Toronto, ON',
    service: 'anti_scam',
    serviceLabel: 'Prévention anti-arnaque — 20/30 min',
    duration: '20-30 min',
    price: '20 à 30 min',
    status: 'slot_proposed',
    clientStatus: 'worker',
    preferredLanguage: 'en',
    message: 'A landlord is asking for a deposit before I visit the apartment.',
    nextAction: 'Attendre confirmation du créneau proposé.',
  },
];

export const mockCases: readonly CaseFile[] = [
  {
    id: 'case_2001',
    clientName: 'Nadia Benali',
    email: 'nadia.benali@example.com',
    cityProvince: 'Montréal, QC',
    status: 'active',
    preferredLanguage: 'fr',
    openedAt: '2026-06-14T16:00:00.000Z',
    lastContactAt: '2026-06-15T12:15:00.000Z',
    nextStep: 'Préparer une checklist personnalisée pour la première semaine.',
    actionPlan: ['NAS', 'Compte bancaire', 'Assurance maladie Québec', 'Téléphone local'],
    internalNotes: ['Cliente arrivée récemment, besoin de priorisation simple.'],
    bookingId: 'bk_1001',
  },
  {
    id: 'case_2002',
    clientName: 'Omar Haddad',
    email: 'omar.haddad@example.com',
    cityProvince: 'Ottawa, ON',
    status: 'waiting_client',
    preferredLanguage: 'ar',
    openedAt: '2026-06-15T10:30:00.000Z',
    nextStep: 'Attendre confirmation de disponibilité.',
    actionPlan: ['Clarifier statut étudiant', 'Lister ressources campus', 'Préparer appel découverte'],
    internalNotes: ['Préférer une réponse courte en arabe.'],
    bookingId: 'bk_1002',
  },
];

export const mockScamChecks: readonly ScamCheck[] = [
  {
    id: 'scam_3001',
    createdAt: '2026-06-15T18:20:00.000Z',
    requesterName: 'Maya Singh',
    email: 'maya.singh@example.com',
    situation: 'Apartment deposit requested before visit, pressure to pay by e-transfer today.',
    amountRequested: '1 200 $',
    urgency: 'high',
    riskLevel: 'high',
    status: 'reviewing',
    notes: ['Demander capture du message sans document sensible.', 'Recommander de ne pas payer avant vérification.'],
  },
  {
    id: 'scam_3002',
    createdAt: '2026-06-16T08:10:00.000Z',
    requesterName: 'Samir El Mansouri',
    email: 'samir.el@example.com',
    situation: "Message prétendant venir d'une banque avec un lien de vérification de compte.",
    urgency: 'normal',
    riskLevel: 'unreviewed',
    status: 'new',
    notes: ['À évaluer.'],
  },
  {
    id: 'scam_3003',
    createdAt: '2026-06-16T11:05:00.000Z',
    requesterName: 'Fatima Zahra Idrissi',
    email: 'fz.idrissi@example.com',
    situation: 'Un employeur demande de payer des frais de formation avant le premier jour de travail.',
    amountRequested: '350 $',
    urgency: 'high',
    riskLevel: 'urgent',
    status: 'new',
    notes: ['Signaux forts : paiement avant embauche officielle, pression temporelle.'],
  },
  {
    id: 'scam_3004',
    createdAt: '2026-06-14T15:30:00.000Z',
    requesterName: 'Karim Boudiaf',
    email: 'k.boudiaf@example.com',
    situation: "Appel d'une personne se présentant comme agent de l'IRCC demandant de confirmer le NAS par téléphone.",
    urgency: 'normal',
    riskLevel: 'medium',
    status: 'reviewing',
    notes: ["L'IRCC ne demande jamais de NAS par téléphone de manière proactive."],
  },
  {
    id: 'scam_3005',
    createdAt: '2026-06-13T09:45:00.000Z',
    requesterName: 'Leila Mansouri',
    email: 'leila.m@example.com',
    situation: "Annonce de logement avec loyer très bas pour Montréal centre-ville, propriétaire à l'étranger.",
    amountRequested: '800 $/mois',
    urgency: 'low',
    riskLevel: 'low',
    status: 'responded',
    notes: ['Conseillé de visiter en personne avant tout paiement. Vérifier via Registre foncier.'],
  },
  {
    id: 'scam_3006',
    createdAt: '2026-06-12T14:20:00.000Z',
    requesterName: 'Yassine Taleb',
    email: 'yassine.t@example.com',
    situation: 'Demande de paiement en cartes-cadeaux reçue par SMS, prétendument de la CRA.',
    amountRequested: '2 000 $',
    urgency: 'high',
    riskLevel: 'urgent',
    status: 'closed',
    notes: ['La CRA ne demande jamais de paiement en cartes-cadeaux. Signalé à Cybercrime.gc.ca.'],
  },
];

export const mockResources: readonly ResourceGuide[] = [
  {
    id: 'res_4001',
    title: 'Première semaine au Canada',
    category: 'first_week',
    locale: 'fr',
    status: 'published',
    updatedAt: '2026-06-10T11:00:00.000Z',
    summary: 'Priorités concrètes pour les premiers jours : documents, banque, téléphone, santé.',
    owner: 'Marhaban Canada',
  },
  {
    id: 'res_4002',
    title: 'Vérifier une annonce de logement',
    category: 'anti_scam',
    locale: 'fr',
    status: 'review',
    updatedAt: '2026-06-12T15:30:00.000Z',
    summary: "Signaux d'alerte et étapes prudentes avant de payer un dépôt.",
    owner: 'Marhaban Canada',
  },
  {
    id: 'res_4003',
    title: 'Banking basics for newcomers',
    category: 'banking',
    locale: 'en',
    status: 'draft',
    updatedAt: '2026-06-13T09:00:00.000Z',
    summary: 'Account opening, secured credit cards, and common banking terms.',
    owner: 'Marhaban Canada',
  },
];
